** Transformation based Code generation for Finite Element Methods
  [Aug, 2018 - Present]
  /Advised by Prof. Andreas Klöckner, UIUC/

  We are extending the loo.py package by enabling transformations that
  would optimize the Finite Element kernels of the Firedrake
  Project(Imperial College), to boost their performance on GPUs.

** Solving Eikonal Equations on Unstructured Grids
  [Dec, 2016 - June 2017]
  /Advised by Prof. S Baskar, IIT Bombay/

  Characteristic Fast Marching Method is widely used in solving the
  Eikonal equations, however previous work had been only formulated for
  structured grids. We developed a solver that extended the algorithm
  for unstructured grids as well. Used the solver to solve known
  problems in literature with skew grids so that the activity of the
  solution could be efficiently observed in the region of activity

** Discontinuous Galerkin Framework for solving Hyperbolic PDEs
  [Dec,2015 - May 2017]
  /Advised by Prof. Shiva Gopalakrishnan, IIT Bombay/

  We developed a C++ library for solving Hyperbolic Equations through
  Discontinuous Galerkin ("DG") methods on structured grids. Performed a
  series of convergence tests to verify that the framework satisfied
  hp−convergence. Eventually, used the framework to simulate problems in
  Fluid Dynamics like the dam-break problem using high order DG
  elements.

** Flow Induced Reconfiguration of Aquatic Vegetation
  [Feb, 2015 - Aug, 2016]
  /Advised by Prof. Rajneesh Bharadwaj, IIT Bombay/
  Corrected the existing models for Fluid Structure Interaction for a
  Flexible plate by including the Skin friction coefficient in the
  computations. Implemented a "Predictor-Corrector" based Finite
  Difference scheme for the computation of coefficient of drag on the
  plate

--------------
